backend - Настройка совместной работы и конфигов Добавили новые контейнеры и пакеты для совместной работы, webpack теперь работает относительно запуска - dev, prod

diff --git a/backend/Dockerfile-Node b/backend/Dockerfile-Node
--- a/backend/Dockerfile-Node
+++ b/backend/Dockerfile-Node
@@ -1,5 +1,5 @@
 # Используем образ линукс Alpine с версией node 14
-FROM node:22-alpine
+FROM node:24-alpine3.22
 
 # Указываем нашу рабочую директорию
 WORKDIR /web-api
@@ -7,14 +7,22 @@ WORKDIR /web-api
 # Скорировать package.json и package-lock.json внутрь контейнера
 COPY package*.json ./
 
-# Устанавливаем зависимости
-RUN npm install
+# Устанавливаем зависимости (Retry Wrapper)
+RUN set -e; \
+  max=5; i=0; \
+  until [ $i -ge $max ]; do \
+    npm ci --prefer-offline --no-audit --progress=false && break; \
+    i=$((i+1)); \
+    echo "npm install failed, attempt $i/$max. sleeping $((i*5))s..."; \
+    sleep $((i*5)); \
+  done; \
+  if [ $i -ge $max ]; then echo "npm ci failed after $max attempts" && exit 1; fi
 
 # Копируем оставшиеся приложения в контейнер
 COPY . . 
 
 # Сборка приложения в /dist
-RUN npm run build
+RUN npm run build:prod
 
 # Открыть порт в нашем контейнер
 EXPOSE 8080
